package controllers;

public enum Commands {
	CHANGE_ENGLISH, CHANGE_SPANISH,OPEN_LENGUAGE_DIALOG,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS,
	REPORT_EIGHT,REPORT_NINE,REPORT_TEN,GRAPHIC_REPORT_ONE,GET_INFO_TABLES;
}
