package controllers;

public enum Commands {
	CHANGE_ENGLISH, CHANGE_SPANISH,EXIT,TABLE_REPORTS,PANEL_INITIAL,GRAPHIC_REPORTS,
	REPORT_EIGHT,REPORT_NINE,REPORT_TEN,GRAPHIC_REPORT_ONE,GET_INFO_TABLES,PANEL_TABLE_CULTIVES,OPEN_DIALOG_ADD,
	GRAPHIC_REPORT_TWO,GRAPHIC_REPORT_SEVEN, GRAPHIC_REPORT_SIX, GRAPHIC_REPORT_FIVE, GRAPHIC_REPORT_FOUR,
	GRAPHIC_REPORT_THREE,CLOSE_DIALOGS,CREATE_CULTIVE;

}
